"""Database creation 1

Revision ID: 1624e8b2edaa
Revises: 6f6603046356
Create Date: 2023-08-16 20:01:36.477511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1624e8b2edaa'
down_revision: Union[str, None] = '6f6603046356'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('orders_user_id_key', 'orders', type_='unique')
    op.create_unique_constraint(None, 'orders', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='unique')
    op.create_unique_constraint('orders_user_id_key', 'orders', ['user_id'])
    # ### end Alembic commands ###
