version: '3.10'

services:
  billing_service:
    build: ./billing_service
    env_file:
      - ./billing_service/.env
    volumes:
      - ./billing_service:/app

  billing_postgres:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "5432:5432"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf:/etc/nginx/conf.d:ro
    ports:
      - "80:80"

volumes:
  postgres_data:
